# Generated by Django 5.2.3 on 2026-03-03 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=255, null=True, verbose_name="Username"
                    ),
                ),
                (
                    "image_before",
                    models.ImageField(
                        null=True,
                        upload_to="profile_image",
                        verbose_name="Before User image",
                    ),
                ),
                (
                    "image_after",
                    models.ImageField(
                        null=True,
                        upload_to="profile_image",
                        verbose_name="After User image",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date of create"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Date of update"),
                ),
                (
                    "workout_minutes",
                    models.IntegerField(default=0, verbose_name="All time workouts"),
                ),
                (
                    "workouts_count",
                    models.IntegerField(default=0, verbose_name="Workouts count"),
                ),
                (
                    "weight_lifted",
                    models.IntegerField(default=0, verbose_name="Weight lifted"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
