# Generated by Django 5.2.3 on 2026-03-06 13:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("exercise", "0002_initial"),
        ("workouts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of workout"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description of workout"),
                ),
                (
                    "duration_minutes",
                    models.IntegerField(
                        default=60, verbose_name="Duration of workout (minutes)"
                    ),
                ),
                ("is_public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workouts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author of workout",
                    ),
                ),
                (
                    "exercises",
                    models.ManyToManyField(
                        to="exercise.exercise", verbose_name="Exercises"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "author"], name="workouts_wo_name_568b5d_idx"
                    )
                ],
            },
        ),
    ]
