# Generated by Django 5.2.3 on 2026-03-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0003_remove_exercise_workout"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="exercises",
            field=models.ManyToManyField(
                to="exercise.exercise", verbose_name="Exercises"
            ),
        ),
    ]
