# Generated by Django 5.2.3 on 2026-03-04 17:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=25, verbose_name="Name of category"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description of category"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=50, verbose_name="Name of exercise"),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description of exercise"),
                ),
                (
                    "icon",
                    models.ImageField(
                        upload_to="exercise_icon", verbose_name="Icon of exercise"
                    ),
                ),
                (
                    "repeat",
                    models.IntegerField(default=0, verbose_name="Count of repeat"),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exercises",
                        to="exercise.category",
                        verbose_name="Category of exercise",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["name", "category"], name="exercise_ex_name_e01347_idx"
                    )
                ],
            },
        ),
    ]
