# Generated by Django 5.2.3 on 2026-03-04 19:16

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0001_initial"),
        ("workouts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="exercise",
            name="workout",
            field=models.ManyToManyField(
                related_name="exercises", to="workouts.workout"
            ),
        ),
        migrations.AlterField(
            model_name="exercise",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
