# Generated by Django 5.2.3 on 2026-03-04 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0002_exercise_workout_alter_exercise_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="workout",
        ),
    ]
