# Generated by Django 5.2.3 on 2026-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0003_alter_category_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="exercise",
            name="icon",
        ),
        migrations.AddField(
            model_name="category",
            name="icon_name",
            field=models.CharField(
                max_length=10, null=True, verbose_name="Name of icon"
            ),
        ),
    ]
