# Generated by Django 5.2.3 on 2026-03-07 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exercise", "0004_remove_exercise_icon_category_icon_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="icon_name",
            field=models.CharField(max_length=10, verbose_name="Name of icon"),
        ),
    ]
